services:
  api:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    env_file: .env

  db:
    image: postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"
    